### ISSUE TITLE
Thanks for posting this to GitHub

### ISSUE THREAD

**Issue by akennel** [Andy-Dawson/SPWakeUp#1]
Hi, I'm the original author. Thanks for picking this up and rehosting it on GitHub.
Happy to see the old code again.

**Comment by Andy-Dawson** [comment]
I'm just hopeful that it's of use to someone!
I used this for pretty much all of the on-site installs that I did, and generated versions for SharePoint 2013/2016. It always seemed like such a simple and elegant solution!
